GmyGold/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('goldprice.urls','goldprice'), namespace='goldprice')),
    path('',include(('user.urls','user'), namespace='user')),
    path('',include(('blog.urls','news'), namespace='news'))

]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from .views import PostCreateView, PostUpdateView, PostDeleteView

urlpatterns = [
    path('news/', views.index, name='home'),
    path('detail/<str:title>/<int:post_id>',views.Post_detail,name='detail'),
    # path('new_post/', PostCreateView.as_view(), name='new_post'),
    # path('detail/<slug:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    # path('detail/<slug:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
]

goldprice/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('gold-price-ounce/', views.gold_ounce, name='ounce'),
    path('silver-price/', views.silver_price, name='silver'),
    # path('articles/<int:year>/', views.year_archive),
]

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static
from django.conf import settings
from .views import ItemCreateView, ItemUpdateView, ItemDeleteView,CustomerSignUpView,VendorSignUpView

# from .views import SingUp,CustomerSignUpView,VendorSignUpView

urlpatterns = [
    path('store', views.index, name='home'),
    path('new_item/', ItemCreateView.as_view(), name='new_item'),
    path('new_item/detail/<str:item_name>/<int:item_id>',views.Item_detail,name='detail'),
    path('new_item/detail/<slug:pk>/update/', ItemUpdateView.as_view(), name='item-update'),
    path('new_item/detail/<slug:pk>/delete/', ItemDeleteView.as_view(), name='item-delete'),

    # path('أضافة منتج جديد/', views.ItemCreateView, name='new_item'),
    path('register/', views.register, name='register'),
    # path('login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('login/', views.login_user, name='login'),
    # path('logout/', LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile_update/', views.profile_update, name='profile_update'),
    
    path('singup/',views.SingUp,name='singup'),
    path('signup/customer/', CustomerSignUpView.as_view(), name='customer_signup'),
    path('signup/vendor/', VendorSignUpView.as_view(), name='vendor_signup'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.utils import timezone
from ckeditor.fields import RichTextField
from django.urls import reverse
from PIL import Image
from django.conf import settings

# Post tabel
class Post(models.Model):
    title = models.CharField(max_length=250, verbose_name='عنوان المقال')
    post_image = models.ImageField(null=True, blank=True, upload_to="images/", verbose_name='صورة المقال')
    content = RichTextField(null=True, blank=True, verbose_name='نص المقال')
    post_date = models.DateTimeField(default=timezone.now)
    post_update = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE , verbose_name='صاحب المقال')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        try:
            image = Image.open(self.post_image.path)
            image.save(self.post_image.path,quality=20,optimize=True)
        except:
            pass
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        #الأخبار/detail/عنوان%2001/13
        #.format(self.pk, self.title)
        return f'/detail/{self.title}/{self.pk}'
        #return reverse('detail', args=[self.title])
        #detail/<str:title>/<int:post_id>
    class Meta:
        ordering = ('-post_date',)

# Comment tabel
class Comment(models.Model):
    name = models.CharField(max_length=50, verbose_name='الاسم')
    email = models.EmailField(verbose_name='البريد الالكتروني')
    title = models.CharField(default='',max_length=200, verbose_name='عنوان التعليق')
    body = models.TextField(verbose_name='التعليق')
    comment_date = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    def __str__(self):
        return 'علق {} على {}.'.format(self.name, self.post)
    class Meta:
        ordering = ('-comment_date',)

class Contact(models.Model):
    name = models.CharField(max_length=50)
    email= models.EmailField(max_length=150)
    subject = models.CharField(max_length=200)
    message = models.TextField()

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Comment, Post
# from django.contrib.auth.models import User
from django.conf import settings

class NowComment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','title','body')
        
class PostCreateForm(forms.ModelForm):
    title = forms.CharField(label='عنوان التدوينة')
    # post_image = forms.ImageField(label='صورة المقال')
    content = forms.CharField(label='نص التدوينة', widget=forms.Textarea)

    class Meta:
        model = Post
        fields = ['title','content']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, PageNotAnInteger,EmptyPage
from django.http import HttpResponseRedirect
from django.contrib import messages
import datetime
from .models import Post,Comment,Contact
from .forms import NowComment, PostCreateForm
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.conf import settings
User = settings.AUTH_USER_MODEL

def index(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, 12)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_page)
    
    context = {
        'title': 'الاخبار',
        'posts': posts,
        'page': page,
    }
    return render(request,'blog/blog.html',context)

def Post_detail(request,title, post_id):
    post = get_object_or_404(Post,pk=post_id)
    posts = Post.objects.all()
    paginator = Paginator(posts, 6)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_page)
    comments = post.comments.filter(active=True)
    comment_form = NowComment()
    next_comment = None
    context = {
            'title': post,
            'post':post,
            'posts': posts,
            'comments':comments,
            'comment_form': comment_form,
    }
   
    if request.method == 'POST':
        comment_form = NowComment(data=request.POST)
        if request.method == 'POST':
            comment_form = NowComment(data=request.POST)
            if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                new_comment.post = post
                new_comment.save()
                comment_form = NowComment()
                next = request.POST.get('next', '/')
                return HttpResponseRedirect(next)
                #messages.success(request,'تم ارسال التعليق بنجاح')
                # return render(request,'blog/comment_render.html')
            else:
                comment_form = NowComment()
    return render(request, 'blog/detail.html',context)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    # fields = ['title', 'content']
    template_name = 'blog/new_post.html'
    form_class = PostCreateForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'blog/post_update.html'
    form_class = PostCreateForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False


class PostDeleteView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ar" dir='rtl'>

    <head>
        <meta charset="utf-8">
        <!--<title>iDESIGN - Interior Design HTML Template</title>-->
        {% if title %}
        <title>{{title}}</title>
        {% else %}
        <title> الذهب اليوم</title>
        {% endif %}
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="Free HTML Templates" name="keywords">
        <meta content="Free HTML Templates" name="description">
        <!--fontawesome kit-->
        <script src="https://kit.fontawesome.com/e0ff260592.js" crossorigin="anonymous"></script>
        <!-- Favicon -->
        <link rel="icon" type="image/png" href="{% static 'goldprice/images/gold-icon.png' %}">
    
        <!-- Google Web Fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Oswald:wght@400;500;600&display=swap" rel="stylesheet"> 
    
        <!-- Font Awesome -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        
        <!-- Google Web Fonts (cairo)-->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300&display=swap" rel="stylesheet">

        <!-- Flaticon Font -->
        <link href="{% static 'blog/lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
    
        <!-- Libraries Stylesheet -->
        <link href="{% static 'blog/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
        <link href="{% static 'blog/lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">
    
        <!-- Customized Bootstrap Stylesheet -->
        <link href="{% static 'goldprice/css/table.css' %}" rel="stylesheet">
        <link href="{% static 'blog/css/style.css' %}" rel="stylesheet">
        <link href="{% static 'goldprice/css/main.css' %}" rel="stylesheet">
    </head>
<body>
   
    <!-- Topbar Start -->
    <div class="container-fluid py-3" style="background-color: #174f96">
        <div class="container mt-2">
            <div class="row top-nav">
                <div class="col-md-6 text-center text-lg-right mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <div class="d-inline-flex align-items-center top-nav">
                            <a class="pr-1 log-in" href="{% url 'user:new_item' %}">منتج جديد</a>
                            <span class="text-white">|</span>
                            <a class="text-white pr-1" href="{% url 'user:profile' %}">الملف الشخصي</a>
                            <span class="text-white">|</span>
                            <a class="text-white pr-1" href="{% url 'user:logout' %}">تسجيل خروج</a>
                            <!--
                            <span class="text-white">|</span>
                            <a class="text-white pr-1" href="">تواصل معنا</a>-->
                        </div>
                    {% else %}
                        <div class="d-inline-flex align-items-center top-nav">
                            <a class="pr-1 log-in" href="{% url 'user:register' %}">تسجيل الدخول</a>
                            <span class="text-white">|</span>
                            <a class="text-white pr-1" href="{% url 'user:login' %}">تسجيل</a>
                            <!--
                            <span class="text-white">|</span>
                            <a class="text-white pr-1" href="">تواصل معنا</a>-->
                        </div>
                    {% endif %}
                </div>
                <div class="col-md-6 text-center text-lg-left">
                    <div class="d-inline-flex align-items-center">
                        <a class="text-white px-3" href="">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a class="text-white px-3" href="">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a class="text-white px-3" href="">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                        <a class="text-white px-3" href="">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <a class="text-white pl-3" href="">
                            <i class="fab fa-youtube"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->
    
    <!-- Navbar Start -->
    <div class="container-fluid position-relative nav-bar p-0 mb-3">
        <div class="container position-relative" style="z-index: 9;background-color: #245ea9; color:#fff">
            <nav class="navbar navbar-light navbar-expand-lg py-3 py-lg-0 pl-3 pl-lg-5">
                <a href="{% url 'goldprice:home' %}" class="navbar-brand">
                    <h1 class="display-5 text-white"><span class="text-primary">ا</span>لذهب اليوم</h1>
                </a>
                <button type="button" class="navbar-toggler text-white" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between px-3" id="navbarCollapse" style="background-color: #245ea9;">
                    <div class="navbar-nav text-right py-0">
                        <a href="{% url 'news:home' %}" class="nav-item nav-link active" style="color: #d09c00 !important;">الأخبار</a>
                        <a href="{% url 'user:home' %}" class="nav-item nav-link">متجر الذهب في ألمانيا</a>
                        <a href="{% url 'goldprice:ounce' %}" class="nav-item nav-link">سعر أونصة الذهب في ألمانيا</a>
                        <a href="{% url 'goldprice:silver' %}" class="nav-item nav-link">سعر الفضة في ألمانيا</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">أسعار الذهب في دول أخرى</a>
                            <div class="dropdown-menu rounded-0 m-0">
                                <a href="{% url 'goldprice:home' %}" class="dropdown-item">سعر الذهب في ألمانيا</a>
                                <a href="#" class="dropdown-item">سعر الذهب في تركيا</a>
                                <a href="#" class="dropdown-item">سعر الذهب في كندا</a>
                                <a href="#" class="dropdown-item">سعر الذهب عالميا بالدولار</a>
                                <a href="#" class="dropdown-item">سعر الذهب في السعودية</a>
                            </div>
                        </div>
                        <!--<a href="#" class="nav-item nav-link">من نحن</a>-->
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <!-- Navbar End -->

    <!-- Under Nav Start -->
    <!--
    <div class="container-fluid bg-white py-3">
        <div class="container">
            <div class="row">
                <div class="col-7 text-left text-lg-center mb-3 mb-lg-0">
                    <div class="d-inline-flex text-right">
                        <h1 class="flaticon-email font-weight-normal text-primary m-0 ml-3"></h1>
                        <div class="d-flex flex-column">
                            <h5>البريد الالكتروني</h5>
                            <p class="m-0">akram@gmail.com</p>
                        </div>
                    </div>
                </div>
                <div class="col-5 text-left text-lg-right mb-3 mb-lg-0">
                    <div class="d-inline-flex text-right">
                        <h1 class="flaticon-telephone font-weight-normal text-primary m-0 ml-3"></h1>
                        <div class="d-flex flex-column">
                            <h5>تواصل معنا</h5>
                            <p class="m-0 ">509626 0761 49+</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    -->
    <!-- Under Nav End -->

    {% block content %}
    {% endblock %}

    <!-- Footer Start -->
    <div class="container-fluid text-white py-5 px-sm-3 px-md-5" style="background-color: #174f96">
        <!--<div class="row pt-5">
            <div class="col-lg-3 col-md-6 mb-5">
                <h4 class="text-primary mb-4">Get In Touch</h4>
                <p><i class="fa fa-map-marker-alt mr-2"></i>Location, City, Country</p>
                <p><i class="fa fa-phone-alt mr-2"></i>+012 345 67890</p>
                <p><i class="fa fa-envelope mr-2"></i>info@example.com</p>
                <div class="d-flex justify-content-start mt-4">
                    <a class="btn btn-outline-light rounded-circle text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light rounded-circle text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light rounded-circle text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-linkedin-in"></i></a>
                    <a class="btn btn-outline-light rounded-circle text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-instagram"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h4 class="text-primary mb-4">Quick Links</h4>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>About Us</a>
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Services</a>
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Projects</a>
                    <a class="text-white" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h4 class="text-primary mb-4">Popular Links</h4>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>About Us</a>
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Services</a>
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Projects</a>
                    <a class="text-white" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h4 class="text-primary mb-4">Newsletter</h4>
                <form action="">
                    <div class="form-group">
                        <input type="text" class="form-control border-0" placeholder="Your Name" required="required" />
                    </div>
                    <div class="form-group">
                        <input type="email" class="form-control border-0" placeholder="Your Email" required="required" />
                    </div>
                    <div>
                        <button class="btn btn-lg btn-primary btn-block border-0" type="submit">Submit Now</button>
                    </div>
                </form>
            </div>
        </div>-->
        <div class="container">
            <p class="m-0 text-center text-white">
                &copy; <a class="text-white font-weight-bold" href="#"> الذهب اليوم</a>. جميع الحقوق محفوظة
                <a class="text-white font-weight-bold" href="#"> الذهب اليوم دوت كوم 2022</a>
            </p>
        </div>
    </div>
    <!-- Footer End -->
    


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg text-white back-to-top" style="display: inline; background-color: #245ea9"><i class="fa fa-angle-double-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'blog/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'blog/lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'blog/lib/isotope/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'blog/lib/lightbox/js/lightbox.min.js' %}"></script>

    <!-- Contact Javascript File -->
    <script src="{% static 'blog/mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{% static 'blog/mail/contact.js' %}"></script>

    <!--Font awesome kite -->
    <script src="https://kit.fontawesome.com/70eaba7a0e.js" crossorigin="anonymous"></script>
    <!-- Template Javascript -->
    <script src="{% static 'blog/js/main.js' %}"></script>
</body>

</html>

templates/blog/blog.html
{% extends 'goldprice/base.html'%}
{% load static %}


<!-- Blog Start -->
{% block content %}
<!-- Page Header Start -->
<div class="container-fluid py-5 gradient-examples">
    <div class="container py-5 example linear">
        <div class="row align-items-center py-4 p-3">
            <div class="col-md-6 text-center text-md-right">
                <h3 class="mb-4 mb-md-0 text-white text-uppercase">آخر الأخبار والتدوينات الخاصة بالذهب وأسعار الذهب</h3>
            </div>
            <div class="col-md-6 text-center text-md-left">
                <div class="d-inline-flex align-items-center ">
                    <a class="btn btn-outline-primary disabled mr-5" href="">الأخبار</a>
                    <i class="fas fa-angle-double-left text-white mx-2"></i>
                    <a class="btn btn-outline-primary" href="{% url 'goldprice:home' %}">اسعار الذهب</a>

                </div>
            </div>
        </div>
    </div>
</div>
<!-- Page Header Start -->
<div class="container-fluid bg-light pt-5">
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8 col text-center mb-4">
                <h1 class="mb-3 dygswC" style="color: rgb(42, 43, 47); font-family: 'Droid Arabic Kufi', Arial, Helvetica, sans-serif;">آخر الأخبار</h1>
                <!--<h2 class="mb-4">أخر الأخبار والتدوينات الخاصة بالذهب وأسعار الذهب</h2>-->
            </div>
        </div>
        <div class="row pb-3">
            {% for post in posts %}
                <div class="col-md-4 mb-4">
                    <div class="card border-0 mb-2">
                        {% if post.post_image %}
                            <img class="card-img-top" src="{{post.post_image.url}}" alt="">
                        {% else %}
                            <img class="card-img-top" src="{% static 'blog/img/defult.jpg' %}" alt="">
                        {% endif %}
                        <div class="card-body bg-white p-4">
                            <div class="d-flex align-items-center mb-3">
                                <a class="btn text-white" href="{% url 'news:detail' post.title post.id %}" style="background-color: #245ea9"><i class="fa fa-link"></i></a>
                                <h5 class="m-0 mr-3 text-truncate">
                                    {{post.title|safe}} 
                                </h5>
                            </div>
                            <p class="text-right">
                                {% if post.content|length > 120 %}
                                    {{post.content|safe|striptags|slice:120}} ...
                                    <a href="{% url 'news:detail' post.title post.id  %}" style="text-shadow: 1px 2px 3px #cc902a;color:#245ea9; text-shadow: 1px 2px 3px #cc902a;color:#245ea9;padding: 0.25rem;">اقرأ المزيد </a>
                                {% else %}
                                    {{post.content|safe}} <a href="{% url 'news:detail' post.title post.id %}" style="text-shadow: 1px 2px 3px #cc902a;color:#245ea9; text-shadow: 1px 2px 3px #cc902a;color:#245ea9;padding: 0.25rem;">اقرأ المزيد </a>
                                {% endif %}</p>
                            <div class="d-flex">
                                <small class=""><i class="fa fa-user text-primary"></i> {{post.author}}</small>
                                <small class="mr-3"><i class="fa fa-folder text-primary"></i> أخبار الذهب</small>
                                <small class="mr-3"><i class="fa fa-clock text-primary"></i> {{post.post_date|date:'d-m-Y'}}</small>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% include 'blog/pagination.html' with page=posts %}
        </div>

    </div>
</div>
{% endblock %}
<!-- Blog End -->

templates/blog/comment_render.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <link rel="stylesheet" href="{% static 'css/main.css' %}">
     <link rel="stylesheet" href="{% static 'css/fontawssom-all.min.css' %}">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title></title>
</head>
<body>
     <div class="alert text-center alert-success m-5" role="alert">
          <h3>تم ارسال تعليقك بنجاح</h3>
          <a href="{% url 'news:home' %}">
               <h4>
                    يمكنك العورة الى صفحة المقالات من هنا <i class="fas fa-angle-double-left"></i>
               </h4>
          </a>
      </div>

      <script src="{% static 'js/main.js' %}"></script>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <script src="https://use.fontawesome.com/4e391d9e65.js"></script>
      <script src="{% static 'js/fontawssom-all.min.js' %}"></script>
</body>
</html>

templates/blog/latest_posts.html
{% load static %}

{% for post in l_posts %}
<div class="d-flex align-items-center border-bottom mb-3 pb-3">
        {% if post.post_image %}
            <img class="img-fluid" src="{{post.post_image.url}}" style="width: 80px; height: 80px;" alt="">
        {% else %}
            <img class="img-fluid" src="{% static 'blog/img/defult.jpg'%}" style="width: 80px; height: 80px;" alt="">
        {% endif %}
        <div class="d-flex flex-column pr-3">
        <a class="text-dark mb-2" href="">{{post.title}}</a>
        <div class="d-flex">
            <small class="mr-2"><i class="fa fa-user text-primary"></i> {{post.author}}</small>
            <small class="mr-3"><i class="fa fa-comments text-primary"></i> {{post.post_date|date:'d-m-Y'}}</small>
    </div>
</div>
</div>
{% endfor %}