GmyGold/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('goldprice.urls','goldprice'), namespace='goldprice')),
    path('',include(('user.urls','user'), namespace='user')),
    path('',include(('blog.urls','news'), namespace='news'))

]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from .views import PostCreateView, PostUpdateView, PostDeleteView

urlpatterns = [
    path('news/', views.index, name='home'),
    path('detail/<str:title>/<int:post_id>',views.Post_detail,name='detail'),
    # path('new_post/', PostCreateView.as_view(), name='new_post'),
    # path('detail/<slug:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    # path('detail/<slug:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
]

goldprice/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('gold-price-ounce/', views.gold_ounce, name='ounce'),
    path('silver-price/', views.silver_price, name='silver'),
    # path('articles/<int:year>/', views.year_archive),
]

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static
from django.conf import settings
from .views import ItemCreateView, ItemUpdateView, ItemDeleteView,CustomerSignUpView,VendorSignUpView

# from .views import SingUp,CustomerSignUpView,VendorSignUpView

urlpatterns = [
    path('store', views.index, name='home'),
    path('new_item/', ItemCreateView.as_view(), name='new_item'),
    path('new_item/detail/<str:item_name>/<int:item_id>',views.Item_detail,name='detail'),
    path('new_item/detail/<slug:pk>/update/', ItemUpdateView.as_view(), name='item-update'),
    path('new_item/detail/<slug:pk>/delete/', ItemDeleteView.as_view(), name='item-delete'),

    # path('أضافة منتج جديد/', views.ItemCreateView, name='new_item'),
    path('register/', views.register, name='register'),
    # path('login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('login/', views.login_user, name='login'),
    # path('logout/', LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile_update/', views.profile_update, name='profile_update'),
    
    path('singup/',views.SingUp,name='singup'),
    path('signup/customer/', CustomerSignUpView.as_view(), name='customer_signup'),
    path('signup/vendor/', VendorSignUpView.as_view(), name='vendor_signup'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goldprice/models.py
from django.db import models

# Create your models here.

goldprice/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger,EmptyPage
from django.http import HttpResponse
from blog.models import Post

# Import libs
from deep_translator import GoogleTranslator
import requests as req
from bs4 import BeautifulSoup as bs
import pandas as pd 
import numpy as np
import json
from datetime import datetime
import plotly.graph_objects as go
import plotly.express as px
from django.conf import settings
User = settings.AUTH_USER_MODEL
# Create your views here.
# make soup function
def make_soup(url):
    r = req.get(url)
    soup = bs(r.content, 'html.parser')
    return soup

def convert_date(n):
    if n == '01':
        month = 'يناير'
        x = '01'
    elif n == '02':
        month = 'فبراير'
        x = '02'
    elif n == '03':
        month = 'مارس'
        x = '03'
    elif n == '04':
        month = 'ابريل'
        x = '04'
    elif n == '05':
        month = 'مايو'
        x = '05'
    elif n == '06':
        month = 'يونيو'
        x = '06'
    elif n == '07':
        month = 'يوليو'
        x = '07'
    elif n == '08':
        month = 'أغسطس'
        x = '08'
    elif n == '09':
        month = 'سبتمبر'
        x = '09'
    elif n == '10':
        month = 'أكتوبر'
        x = '10'
    elif n == '11':
        month = 'نوفمبر'
        x = '11'
    else :
        month = 'ديسمبر'
        x = '12'
    return month , x

def convert_days_ar(day):
    if day == 'Mon':
        day_ar = 'الاثنين'
    elif day == 'Tue':
        day_ar = 'الثلاثاء'
    elif day == 'Wed':
        day_ar = 'الأربعاء'
    elif day == 'Thu':
        day_ar = 'الخميس'
    elif day == 'Sun':
        day_ar = 'الأحد'
    elif day == 'Sat':
        day_ar = 'السبت'
    elif day == 'Today':
        day_ar = 'اليوم'
    elif day == 'Yesterday':
        day_ar = 'البارحة'
    else:
        day_ar = 'الجمعة'
    return day_ar

def convert_date_str(n):
    if n == 'Jan':
        month = 'يناير'
        x = '01'
    elif n == 'Feb':
        month = 'فبراير'
        x = '02'
    elif n == 'Mar':
        month = 'مارس'
        x = '03'
    elif n == 'Apr':
        month = 'ابريل'
        x = '04'
    elif n == 'May':
        month = 'مايو'
        x = '05'
    elif n == 'Jun':
        month = 'يونيو'
        x = '06'
    elif n == 'Jul':
        month = 'يوليو'
        x = '07'
    elif n == 'Aug':
        month = 'أغسطس'
        x = '08'
    elif n == 'Sep':
        month = 'سبتمبر'
        x = '09'
    elif n == 'Oct':
        month = 'أكتوبر'
        x = '10'
    elif n == 'Nov':
        month = 'نوفمبر'
        x = '11'
    else :
        month = 'ديسمبر'
        x = '12'
    return month , x

# Chart function
def make_chart(df,x,y,title,html_file_name,marker):
    # fig = px.line(df.head(n_of_days).loc[::-1], x=x, y=y, markers=False, title=title) 
    x = df[x].loc[::-1]
    y = df[y].loc[::-1]
    fig = go.Figure(data = go.Scatter(x=x, y=y, mode='lines+markers'))
    
    # fig = px.line(df.loc[::-1], x=x, y=y, markers=marker, title=title) 
    fig.update_layout(title=title,)
    fig.update_layout(modebar_bgcolor="yellowgreen")
    fig.update_layout(title_font_color="#333")
    fig.update_layout(title_font_size=18)
    fig.update_layout(title_x=0.5)  
    fig.write_html(html_file_name)

def make_chart_3years(df,x,y,title,html_file_name):
    fig = px.line(df.loc[::-1], x=x, y=y, markers=False, title=title) 
    # fig.show()
    # fig.update_xaxes(rangeslider_visible=True)
    fig.write_html(html_file_name)

# History of 24k Gold Price per Ounce
def history_of_ounce():
    url = 'http://goldpricez.com/eu/ounce'
    soup = make_soup(url)
    table = soup.find('table',{'id':'historymain_table_gold1'})
    trs = table.find_all('tr')
    trs.pop(0)
    data_ounce = []
    for tr in trs:
        d = {}
        pattern = r"[0-9]+"
        import re
        tds = tr.find_all('td')
        # print(tds[0].get_text().split())
        day_num = ''
        month = ''
        if len(tds[0].get_text().split()) > 1:
            day_num = re.search(pattern, tds[0].get_text().split()[1]).group(0)
            month , x = convert_date_str(tds[0].get_text().split()[1])
        date = convert_days_ar(tds[0].get_text().split()[0].split(',')[0]) + ' ' + day_num + ' ' + month
        d['date'] = date
        price = tds[1].get_text().split()[0].replace('€','')
        # print(price)
        d['price'] = price
        data_ounce.append(d)
        
    pd.DataFrame(data_ounce).to_csv('./static/goldprice/csv/history_of_ounce.csv', index=False)
  
# Gold price per karat
def get_tableData_karat():
    links = [('eur',"https://www.livepriceofgold.com/germany-gold-price.html"),('usd',"https://www.livepriceofgold.com/us-gold-price.html")]
    
    def karat(i):
        for j in range(7):
            if i == 1:
                karat = "عيار سعر الذهب عيار 24 قيراط"
            elif i == 2:
                karat = "سعر الذهب عيار 22 قيراط"
            elif i == 3:
                karat = "سعر الذهب عيار 21 قيراط"
            elif i == 4:
                karat = "سعر الذهب عيار 18 قيراط"
            elif i == 5:
                karat = "سعر الذهب عيار 14 قيراط"
            elif i == 6:
                karat = "سعر الذهب عيار 10 قيراط"
            elif i == 7:
                karat = "سعر الذهب عيار 6 قيراط"
            else:
                print("Error in data list")
            break
           
        return karat
    
    data_gram = []
    price_list = []
    def get_data_gram(tables):
        trs = tables[0].find_all('tr')
        trs.pop(0)
        i = 1
        for tr in trs:
            d, d1 = {}, {}
            tds = tr.find_all('td')
            tds.pop(0)
            karat1 = karat(i)
            i += 1
            color = tds[3].get("class")[0]
            if color == 'green-font':
                val = True
            else:
                val = False
            d['color'] = val
            d['change'] = tds[3].get_text()
            d['low'] = tds[2].get_text()
            d['high'] = tds[1].get_text()
            d['price'] = tds[0].get_text()
            d['karat'] = karat1
            d1['karat'] = karat1
            d1['gram'] = d['price']
            price_list.append(d1)
            d['currency'] = link[0]
            data_gram.append(d)
            
        return data_gram, price_list

    data_onece = []
    def get_data_onece(tables):
        trs = tables[1].find_all('tr')
        trs.pop(0)
        i = 1
        for tr in trs:
            d, d1 = {}, {}
            tds = tr.find_all('td')
            tds.pop(0)
            karat1 = karat(i)
            i += 1
            color = tds[3].get("class")[0]
            if color == 'green-font':
                val = True
            else:
                val = False
            d['color'] = val
            d['change'] = tds[3].get_text()
            d['low'] = tds[2].get_text()
            d['high'] = tds[1].get_text()
            d['ounce'] = tds[0].get_text()
            d['karat'] = karat1
            d['currency'] = link[0]
            data_onece.append(d)
        return data_onece
    
    data_kg = []
    def get_data_kg(tables):
        trs = tables[2].find_all('tr')
        trs.pop(0)
        i = 1
        for tr in trs:
            d = {}
            tds = tr.find_all('td')
            tds.pop(0)
            karat1 = karat(i)
            i += 1
            if karat1 == "سعر الذهب عيار 21 قيراط":
                if link[0] == "eur":
                    url = "http://goldpricez.com/eu/21k/kg"
                    soup = make_soup(url)
                    kg_eur = soup.find('div',{'class': 'gold_panel'}).find_all('tr')[0].find_all('td')[1].get_text()
                    kg_eur = kg_eur.split()[0]
                    d['kg'] = kg_eur + ".00"
                    d['karat'] = karat1
                    d['currency'] = link[0]
                    p = tds[0].get_text()
                    test = False
                else:
                    url = "http://goldpricez.com/us/21k/kg"
                    soup = make_soup(url)
                    kg_usd = soup.find('div',{'class': 'gold_panel'}).find_all('tr')[0].find_all('td')[1].get_text()
                    kg_usd = kg_usd.split()[0]
                    d['kg'] = kg_usd + ".00"
                    d['karat'] = karat1
                    d['currency'] = link[0]
                    p = tds[0].get_text()
            else:
                try:
                    d['kg'] = p
                    d['karat'] = karat1
                    d['currency'] = link[0]
                    p = tds[0].get_text()
                except:
                    d['kg'] = tds[0].get_text()
                    d['karat'] = karat1
                    d['currency'] = link[0]
                
            data_kg.append(d)
        d = {}
        d['kg'] = p
        d['karat'] = karat1
        d['currency'] = link[0]
        data_kg.append(d)
        return data_kg
        
    data_tola = []
    def get_data_tola(tables):
        trs = tables[3].find_all('tr')
        trs.pop(0)
        i = 1
        for tr in trs:
            d = {}
            tds = tr.find_all('td')
            tds.pop(0)
            karat1 = karat(i)
            i += 1
            if karat1 == "سعر الذهب عيار 21 قيراط":
                if link[0] == "eur":
                    url = "http://goldpricez.com/eu/21k/tola-india"
                    soup = make_soup(url)
                    tola_eur = soup.find('div',{'class': 'gold_panel'}).find_all('tr')[0].find_all('td')[1].get_text()
                    tola_eur = tola_eur.split()[0]
                    d['tola'] = tola_eur
                    d['karat'] = karat1
                    d['currency'] = link[0]
                    p = tds[0].get_text()
                else:
                    url = "http://goldpricez.com/us/21k/tola-india"
                    soup = make_soup(url)

templates/goldprice/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ar" dir='rtl' style="background-color: #fff ! important">
    <head>
        <meta charset="UTF-8">
        <!--<title>iDESIGN - Interior Design HTML Template</title>-->
        {% if title %}
        <title>{{title}}</title>
        {% else %}
        <title> الذهب اليوم</title>
        {% endif %}
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="Free HTML Templates" name="keywords">
        <meta content="Free HTML Templates" name="description">
        <!--fontawesome kit-->
        <script src="https://kit.fontawesome.com/e0ff260592.js" crossorigin="anonymous"></script>
        <!-- Favicon -->
        <link rel="icon" type="image/png" href="{% static 'goldprice/images/gold-icon.png' %}">
    
        <!-- Google Web Fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Oswald:wght@400;500;600&display=swap" rel="stylesheet"> 
    
        <!-- Font Awesome -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        
        <!-- Google Web Fonts (cairo)-->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300&display=swap" rel="stylesheet">

        <!-- Flaticon Font -->
        <link href="{% static 'blog/lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
    
        <!-- Libraries Stylesheet -->
        <link href="{% static 'blog/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
        <link href="{% static 'blog/lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">
    
        <!-- Additional CSS Files -->
        <link rel="stylesheet" href="{% static 'user/css/fontawesome.css' %}">
        <link rel="stylesheet" href="{% static 'user/css/tooplate-main.css' %}">
        <link rel="stylesheet" href="{% static 'user/css/owl.css' %}">
        <link rel="stylesheet" href="{% static 'user/css/flex-slider.css' %}">
        
        
        <!-- Customized Bootstrap Stylesheet -->
        <link href="{% static 'goldprice/css/table.css' %}" rel="stylesheet">
        <link href="{% static 'blog/css/style.css' %}" rel="stylesheet">
        <link href="{% static 'goldprice/css/main.css' %}" rel="stylesheet">
    </head>
<body>
    
    <!-- Topbar Start -->
    <div class="container-fluid py-3" style="background-color: #174f96">
        <div class="container mt-2">
            <div class="row top-nav">
                <div class="col-md-6 text-center text-lg-right mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <div class="d-inline-flex align-items-center top-nav">
                            {% if not user.is_customer %}
                            <a class="pr-1 log-in" href="{% url 'user:new_item' %}">منتج جديد</a>
                            <span class="text-white">|</span>
                            {%endif%}
                            <a class="text-white pr-1" href="{% url 'user:profile' %}">الملف الشخصي</a>
                            <span class="text-white">|</span>
                            <a class="text-white pr-1" href="{% url 'user:logout' %}">تسجيل خروج</a>
                            <!--
                            <span class="text-white">|</span>
                            <a class="text-white pr-1" href="">تواصل معنا</a>-->
                        </div>
                    {% else %}
                        <div class="d-inline-flex align-items-center top-nav">
                            <a class="pr-1 log-in" href="{% url 'user:login' %}">تسجيل الدخول</a>
                            <span class="text-white">|</span>
                            <a class="text-white pr-1" href="{% url 'user:singup' %}">تسجيل</a>
                            <!--
                            <span class="text-white">|</span>
                            <a class="text-white pr-1" href="">تواصل معنا</a>-->
                        </div>
                    {% endif %}
                </div>
                <div class="col-md-6 text-center text-lg-left">
                    <div class="d-inline-flex align-items-center">
                        <a class="text-white px-3" href="">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a class="text-white px-3" href="">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a class="text-white px-3" href="">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                        <a class="text-white px-3" href="">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <a class="text-white pl-3" href="">
                            <i class="fab fa-youtube"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->
    
    <!-- Navbar Start -->
    <div class="container-fluid position-relative nav-bar p-0 mb-3">
        <div class="container position-relative" style="z-index: 9;background-color: #245ea9; color:#fff">
            <nav class="navbar navbar-light navbar-expand-lg py-3 py-lg-0 pl-3 pl-lg-5">
                <a href="{% url 'goldprice:home' %}" class="navbar-brand">
                    <h1 class="display-5 text-white"><span class="text-primary">ا</span>لذهب اليوم</h1>
                </a>
                <button type="button" class="navbar-toggler text-white" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between px-3" id="navbarCollapse" style="background-color: #245ea9;">
                    <div class="navbar-nav text-right py-0">
                        <a href="{% url 'news:home' %}" class="nav-item nav-link active" style="color: #d09c00 !important;">الأخبار</a>
                        <a href="{% url 'user:home' %}" class="nav-item nav-link">متجر الذهب في ألمانيا</a>
                        <a href="{% url 'goldprice:ounce' %}" class="nav-item nav-link">سعر أونصة الذهب في ألمانيا</a>
                        <a href="{% url 'goldprice:silver' %}" class="nav-item nav-link">سعر الفضة في ألمانيا</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">أسعار الذهب في دول أخرى</a>
                            <div class="dropdown-menu rounded-0 m-0">
                                <a href="{% url 'goldprice:home' %}" class="dropdown-item">سعر الذهب في ألمانيا</a>
                                <!--
                                <a href="#" class="dropdown-item">سعر الذهب في تركيا</a>
                                <a href="#" class="dropdown-item">سعر الذهب في كندا</a>
                                <a href="#" class="dropdown-item">سعر الذهب عالميا بالدولار</a>
                                <a href="#" class="dropdown-item">سعر الذهب في السعودية</a>
                                -->
                            </div>
                        </div>
                        <!--<a href="#" class="nav-item nav-link">من نحن</a>-->
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <!-- Navbar End -->
    
    <!-- header image -->
    <div id="content-div" class="container shadow p-3 mb-5 rounded border-bottom border-primary" style="max-width: 1110px;">
        
        <!-- block content -->
        {% block content %}

        {% endblock %}
        <!-- end content block -->
    </div>
    
    
    <!-- Footer Start -->
    <div class="container-fluid text-white py-5 px-sm-3 px-md-5" style="background-color: #174f96">
        <!--<div class="row pt-5">
            <div class="col-lg-3 col-md-6 mb-5">
                <h4 class="text-primary mb-4">Get In Touch</h4>
                <p><i class="fa fa-map-marker-alt mr-2"></i>Location, City, Country</p>
                <p><i class="fa fa-phone-alt mr-2"></i>+012 345 67890</p>
                <p><i class="fa fa-envelope mr-2"></i>info@example.com</p>
                <div class="d-flex justify-content-start mt-4">
                    <a class="btn btn-outline-light rounded-circle text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light rounded-circle text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light rounded-circle text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-linkedin-in"></i></a>
                    <a class="btn btn-outline-light rounded-circle text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-instagram"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h4 class="text-primary mb-4">Quick Links</h4>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>About Us</a>
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Services</a>
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Projects</a>
                    <a class="text-white" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h4 class="text-primary mb-4">Popular Links</h4>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>About Us</a>
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Services</a>
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Projects</a>
                    <a class="text-white" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h4 class="text-primary mb-4">Newsletter</h4>
                <form action="">
                    <div class="form-group">
                        <input type="text" class="form-control border-0" placeholder="Your Name" required="required" />
                    </div>
                    <div class="form-group">
                        <input type="email" class="form-control border-0" placeholder="Your Email" required="required" />
                    </div>
                    <div>
                        <button class="btn btn-lg btn-primary btn-block border-0" type="submit">Submit Now</button>
                    </div>
                </form>
            </div>
        </div>-->
        <div class="container">
            <p class="m-0 text-center text-white">
                &copy; <a class="text-white font-weight-bold" href="#"> الذهب اليوم</a>. جميع الحقوق محفوظة
                <a class="text-white font-weight-bold" href="#"> الذهب اليوم دوت كوم 2022</a>
            </p>
        </div>
    </div>
    <!-- Footer End -->
    
    <!-- Back to Top -->
    <a href="#" class="btn btn-lg text-white back-to-top" style="display: inline; background-color: #245ea9"><i class="fa fa-angle-double-up"></i></a>
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'blog/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'blog/lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'blog/lib/isotope/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'blog/lib/lightbox/js/lightbox.min.js' %}"></script>

    <!-- Contact Javascript File -->
    <script src="{% static 'blog/mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{% static 'blog/mail/contact.js' %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static 'user/js/custom.js' %}"></script>
    <script src="{% static 'user/js/owl.js' %}"></script>
    <script src="{% static 'user/js/isotope.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'blog/js/main.js' %}"></script>


</body>
</html>

templates/goldprice/header.html
{% load static %}
<!-- header image -->

<div class="container">
    <!--
    <img class="img-fluid border-bottom border-top border-primary" src="{% static 'goldprice/images/header.png' %}" alt="">
    -->
</div>
<!--end header image -->
    <!-- intro -->
<div class="gradient-examples">
<div class="container border rounded border-primary example linear" id="intro">
    <div class="border rounded border-primary text-right mt-3 mb-3 p-3">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <h2 style="text-shadow: 2px 1px 2px #ff8a00"> 
                    <img class="img-fluid" src="{% static 'goldprice/images/gold-icon.png'%}" width="32" alt="">
                    نظرة على اسعار الذهب اليوم في ألمانيا
                </h2>
                <div class="mt-3 mb-3" style="border-bottom: 2px solid #FFCC33;"></div>
                <p class="mb-3">
                    اسعار الذهب اليوم ..اسعار الذهب اليوم هي خدمة مجانية تحرص منصتنا على تقديمها للزائرين ليكونوا مطلعين باستمرار ولحظيا على سعر الذهب اليوم في ألمانيا .. 
                    اسعار الذهب اليوم ..اسعار الذهب اليوم هي خدمة مجانية تحرص منصتنا على تقديمها للزائرين ليكونوا مطلعين باستمرار ولحظيا على سعر الذهب اليوم في ألمانيا ..
                    
                </p>
                <h5>
                    <a class="text-white" href="" style="font-size: 12px;" title="الصفحة الرئيسية لموقع الذهب اليوم">{{title}} » 
                        أخر تحديث لاسعار الذهب والفضة اليوم : <span style="color: black;font-weight: bold;">{{date}}</span></a>
                </h5>
            </div>
            <div class="col-md-4 col-sm-12 text-center">
                <img class="img-responsive rounded" id="logo-ban" src="{% static 'goldprice/images/germany_flag.jpeg'%}" alt="">
            </div>
        </div>
        
    </div>
</div>
</div>
<!-- end intro -->