GmyGold/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('goldprice.urls','goldprice'), namespace='goldprice')),
    path('',include(('user.urls','user'), namespace='user')),
    path('',include(('blog.urls','news'), namespace='news'))

]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from .views import PostCreateView, PostUpdateView, PostDeleteView

urlpatterns = [
    path('news/', views.index, name='home'),
    path('detail/<str:title>/<int:post_id>',views.Post_detail,name='detail'),
    # path('new_post/', PostCreateView.as_view(), name='new_post'),
    # path('detail/<slug:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    # path('detail/<slug:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
]

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static
from django.conf import settings
from .views import ItemCreateView, ItemUpdateView, ItemDeleteView,CustomerSignUpView,VendorSignUpView

# from .views import SingUp,CustomerSignUpView,VendorSignUpView

urlpatterns = [
    path('store', views.index, name='home'),
    path('new_item/', ItemCreateView.as_view(), name='new_item'),
    path('new_item/detail/<str:item_name>/<int:item_id>',views.Item_detail,name='detail'),
    path('new_item/detail/<slug:pk>/update/', ItemUpdateView.as_view(), name='item-update'),
    path('new_item/detail/<slug:pk>/delete/', ItemDeleteView.as_view(), name='item-delete'),

    # path('أضافة منتج جديد/', views.ItemCreateView, name='new_item'),
    path('register/', views.register, name='register'),
    # path('login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('login/', views.login_user, name='login'),
    # path('logout/', LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile_update/', views.profile_update, name='profile_update'),
    
    path('singup/',views.SingUp,name='singup'),
    path('signup/customer/', CustomerSignUpView.as_view(), name='customer_signup'),
    path('signup/vendor/', VendorSignUpView.as_view(), name='vendor_signup'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/forms.py
from django import forms
# from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from .models import Item, Profile, Customer, User,Vendor
from ckeditor.fields import RichTextField

class CustomerSignUpForm(UserCreationForm):
    username = forms.CharField(label='اسم المستخدم', max_length=30,
                               help_text='اسم المستخدم يجب ألا يحتوي على مسافات.')
    email = forms.EmailField(label='البريد الإلكتروني')
    first_name = forms.CharField(label='الاسم الأول')
    last_name = forms.CharField(label='الاسم الأخير')
    password1 = forms.CharField(
        label='كلمة المرور', widget=forms.PasswordInput(), min_length=8)
    password2 = forms.CharField(
        label='تأكيد كلمة المرور', widget=forms.PasswordInput(), min_length=8)
  
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name',
                  'last_name', 'password1', 'password2')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('كلمة المرور غير متطابقة')
        return cd['password2']

    def clean_username(self):
        cd = self.cleaned_data
        if User.objects.filter(username=cd['username']).exists():
            raise forms.ValidationError('يوجد مستخدم مسجل بهذا الاسم.')
        return cd['username']
    
    
    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.email=self.cleaned_data.get('email')
        user.is_customer = True
        user.save()
        customer = Customer.objects.create(user=user)
        return user

class VendorSignUpForm(UserCreationForm):
    username = forms.CharField(label='اسم المستخدم', max_length=30,
                               help_text='اسم المستخدم يجب ألا يحتوي على مسافات.')
    email = forms.EmailField(label='البريد الإلكتروني')
    first_name = forms.CharField(label='الاسم الأول')
    last_name = forms.CharField(label='الاسم الأخير')
    phone=forms.CharField(required=True,label='رقم الهاتف')
    address=forms.CharField(required=True,label='العنوان')
    password1 = forms.CharField(
        label='كلمة المرور', widget=forms.PasswordInput(), min_length=8)
    password2 = forms.CharField(
        label='تأكيد كلمة المرور', widget=forms.PasswordInput(), min_length=8)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name',
                  'last_name', 'password1', 'password2')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('كلمة المرور غير متطابقة')
        return cd['password2']

    def clean_username(self):
        cd = self.cleaned_data
        if User.objects.filter(username=cd['username']).exists():
            raise forms.ValidationError('يوجد مستخدم مسجل بهذا الاسم.')
        return cd['username']

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.email=self.cleaned_data.get('email')
        user.is_vendor = True
        user.save()
        vendor = Vendor.objects.create(user=user)
        vendor.phone=self.cleaned_data.get('phone')
        vendor.address=self.cleaned_data.get('address')
        vendor.save()

        return vendor


class UserCreationForm(forms.ModelForm):
    username = forms.CharField(label='اسم المستخدم', max_length=30,
                               help_text='اسم المستخدم يجب ألا يحتوي على مسافات.')
    email = forms.EmailField(label='البريد الإلكتروني')
    first_name = forms.CharField(label='الاسم الأول')
    last_name = forms.CharField(label='الاسم الأخير')
    password1 = forms.CharField(
        label='كلمة المرور', widget=forms.PasswordInput(), min_length=8)
    password2 = forms.CharField(
        label='تأكيد كلمة المرور', widget=forms.PasswordInput(), min_length=8)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name',
                  'last_name', 'password1', 'password2')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('كلمة المرور غير متطابقة')
        return cd['password2']

    def clean_username(self):
        cd = self.cleaned_data
        if User.objects.filter(username=cd['username']).exists():
            raise forms.ValidationError('يوجد مستخدم مسجل بهذا الاسم.')
        return cd['username']


class LoginForm(forms.ModelForm):
    username = forms.CharField(label='اسم المستخدم')
    password = forms.CharField(
        label='كلمة المرور', widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')


class UserUpdateForm(forms.ModelForm):
    first_name = forms.CharField(label='الاسم الأول')
    last_name = forms.CharField(label='الاسم الأخير')
    email = forms.EmailField(label='البريد الإلكتروني')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('image',)


class ItemCreateForm(forms.ModelForm):
    '''item_name = forms.CharField(label='عنوان المنتج')
    # item_image = forms.ImageField(label='صورة المنتج')
    price = forms.FloatField(label='سعر المنتج')
    phone_numb = forms.CharField(label='رقم الهاتف')
    address = forms.CharField(label='العنوان')
    description = forms.CharField(label='وصف المنتج', widget=forms.Textarea)

    item_image = forms.ImageField()'''
    # content = forms.CharField(label='نص التدوينة', widget=forms.Textarea)
    item_name = forms.CharField(label='عنوان المنتج')
    item_name.widget.attrs.update(size='120')
    description = forms.CharField(label='وصف المنتج', widget=forms.Textarea)
    class Meta:
        model = Item
        fields = ['item_name','item_image','price','phone_numb','address','description']
        

user/views.py
from multiprocessing import context
from django.shortcuts import render, redirect, get_object_or_404,HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from blog.models import Post
from .models import Item,Customer,Vendor
from .forms import UserCreationForm,LoginForm,UserUpdateForm,ProfileUpdateForm,ItemCreateForm,CustomerSignUpForm,VendorSignUpForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from deep_translator import GoogleTranslator
from datetime import datetime
from .filters import ItemFilter
from django.urls import reverse
from django.urls import reverse_lazy

from django.conf import settings
User = settings.AUTH_USER_MODEL

def SingUp(request):
    context = {
        'title': 'تسجيل حساب'
    }
    return render(request,'user/singup.html',context)

class CustomerSignUpView(CreateView):
    model = User
    form_class = CustomerSignUpForm
    template_name = 'user/customer_signup.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('user:login')

class VendorSignUpView(CreateView):
    model = User
    form_class = VendorSignUpForm
    template_name = 'user/vendor_signup.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'teacher'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        #login(self.request, user)
        return redirect('user:login')

def index(request):
    items = Item.objects.all()
    f = ItemFilter(request.GET, queryset=items)
    items = f.qs
    
    paginator = Paginator(items, 12)
    page = request.GET.get('page')
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_page)
    
    now = datetime.now().strftime("%d %B %Y")
    time = datetime.now().strftime("%H:%M") + ' AM'
    month = now.split()[1]
    translated = GoogleTranslator(source='auto', target='ar').translate(month)
    date_now = now.replace(month,translated) 
    
    context = {
        'title': 'متجر الذهب في ألمانيا',
        'items': items,
        'filter': f,
        'page': page,
        'date': date_now,
    }
    return render(request,'user/store.html',context)

def Item_detail(request,item_name, item_id):
    item = get_object_or_404(Item,pk=item_id)
    items = Item.objects.all()
    paginator = Paginator(items, 12)
    page = request.GET.get('page')
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_page)
    context = {
            'title': item,
            'item':item,
            'items': items,
    }
    
    return render(request, 'user/detail.html',context)

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            #username = form.cleaned_data['username']
            new_user.set_password(form.cleaned_data['password1'])
            new_user.save()
            # messages.success(
            #    request, 'تهانينا {} لقد تمت عملية التسجيل بنجاح.'.format(username))
            messages.success(
                request, f'تهانينا {new_user} لقد تمت عملية التسجيل بنجاح.')
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'user/register.html', {
        'title': 'التسجيل',
        'form': form,
    })


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('user:profile')
        else:
            messages.warning(
                request, 'هناك خطأ في اسم المستخدم أو كلمة المرور.')

    return render(request, 'user/login.html', {
        'title': 'تسجيل الدخول',
    })


def logout_user(request):
    logout(request)
    return render(request, 'user/logout.html', {
        'title': 'تسجيل الخروج'
    })


@login_required(login_url='login')
def profile(request):
    items = Item.objects.filter(author=request.user)
    item_list = Item.objects.filter(author=request.user)
    paginator = Paginator(item_list, 8)
    page = request.GET.get('page')
    try:
        item_list = paginator.page(page)
    except PageNotAnInteger:
        item_list = paginator.page(1)
    except EmptyPage:
        item_list = paginator.page(paginator.num_page)
    return render(request, 'user/profile.html', {
        'title': 'الملف الشخصي',
        'items': items,
        'page': page,
        'item_list': item_list,
    })


@login_required(login_url='login')
def profile_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid and profile_form.is_valid:
            user_form.save()
            profile_form.save()
            messages.success(
                request, 'تم تحديث الملف الشخصي.')
            return redirect('user:profile')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'title': 'تعديل الملف الشخصي',
        'user_form': user_form,
        'profile_form': profile_form,
    }

    return render(request, 'user/profile_update.html', context)


class ItemCreateView(LoginRequiredMixin, CreateView):
    model = Item
    # fields = ['title', 'content']
    template_name = 'user/new_item.html'
    form_class = ItemCreateForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
class ItemUpdateView(UserPassesTestMixin, LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Item
    template_name = 'user/item_update.html'
    form_class = ItemCreateForm
    success_url = reverse_lazy('user:profile')
    success_message = f'تم تحديث معلومات المنتج بنجاح .!!!'
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        item = self.get_object()
        if self.request.user == item.author:
            return True
        else:
            return False
        
    '''def get_success_url(self):
        # view_name = 'item_update'
        # No need for reverse_lazy here, because it's called inside the method
        # return reverse_lazy(view_name, kwargs={self.kwargs.get('model_name_slug','')})
        return reverse('user:profile')'''


class ItemDeleteView(UserPassesTestMixin, LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Item
    # success_url = reverse_lazy('user:profile')
    # success_message = 'تم حذف المنتج بنجاح .!!!'
    
    def test_func(self):
        item = self.get_object()
        if self.request.user == item.author:
            return True
        return False

    def get_success_url(self):
        item = self.get_object()
        
        messages.success(self.request, f"تم حذف المنتج بنجاح . {item.item_name}")
        return reverse("user:profile")

templates/user/detail.html
{% extends 'goldprice/base.html'%}
{% load static %}
{% load post_tag %}
{% block content %}
    <!-- Page Content -->
    <!-- Single Starts Here -->
    <div class="single-product text-right">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
                <div class="section-heading">
                  <div class="line-dec"></div>
                  <div class="row">
                    <div class="col-md-4"><h1 class="mr-5">صفحة التفاصيل</h1></div>
                    <div class="col-md">
                      <div class="form-group">
                        {% if item.author == user %}
                            <a class="btn btn-info " href="{% url 'user:item-update' item.id %}">تعديل</a>
                            <a class="btn btn-danger " href="{% url 'user:item-delete' item.id %}">حذف</a>
                        
                        {% endif %}
                    </div>
                    </div>
                  </div>
                </div>
                
              </div>
            <div class="col-md-6">
                <div class="right-content">
                  <h4>{{item.item_name}}</h4>
                  <div class="d-index-flex mb-2"></div>
                    
                  <h6>السعر: {{item.price}}$</h6>
                  <p>{{item.description|safe}}</p>
                  <span class="hidden-phone mb-1 text-secondary">رقم الهاتف: {{item.phone_numb}}</span>
                  <br>
                  <span class="hidden-phone mb-1 text-secondary">العنوان: {{item.address}}</span>
                  <div class="down-content">
                    <div class="categories">
                      <h6>الفئة: <span> الذهب، أكسسوارات الذهب</span></h6>
                    </div>
                    
                  </div>
                </div>
            </div>
            <div class="col-md-6">
                <div style="padding: 20px;border: 1px solid #eee!important;border-radius: 5px">
                    <img src="{{item.item_image.url}}" alt="" style="max-width: 100%;">
                </div>
            </div>
          </div>
        </div>
    </div>
    <!-- Single Page Ends Here -->
    <!-- Similar Starts Here -->
      <div>
        <div class="section-heading text-right">
          <div class="line-dec"></div>
          <h1 class="mr-5">ربما يعجبك أيضا</h1>
        </div>
        <div class="featured container no-gutter">
          <div class="row items">
              {% for item in items %}
              <div class="item new col-md-3">
              <a href="{% url 'user:detail' item.item_name item.id %}">
                  <div class="featured-item">
                      {% if item.item_image %}
                              <img src="{{item.item_image.url}}" alt="">
                          {% else %}
                              <img class="card-img-top" src="{% static 'blog/img/defult.jpg' %}" alt="">
                      {% endif %}
                  <!--<img src="{% static 'user/images/product-01.jpg'%}" alt="">-->
                  <h4>{{item.item_name|safe}} </h4>
                  <h6 class="mb-1"><span>£</span> {{item.price}} </h6>
                  <p class="mb-0"><i class="fa fa-phone" aria-hidden="true"></i> الهاتف: {{item.phone_numb}}</p>
                  <p><i class="fa fa-map-marker" aria-hidden="true"></i> العنوان: {{item.address}}</p>
                  
                  </div>
              </a>
              </div>
              {% endfor %}
              {% include 'blog/pagination.html' with page=items %}
          </div>
        </div>
      </div>
      <!-- Similar Ends Here -->
  
{% endblock %}

templates/user/item_confirm_delete.html
{% extends 'goldprice/base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<div class="gradient-examples">
    <div class="border p-4 mb-5 mt-4 text-right example linear">
        <legend class="border-bottom pb-1 mb-3 text-dark">حذف المنتج</legend>
        <form method="POST">
            <legend class="pb-1 mb-3 mt-4 text-dark">هل أنت متأكد من <strong>حذف</strong> <a href="{% url 'user:detail' item.item_name item.id %}"><span class="text-white">"{{item.item_name}}"؟ </span></a></legend>
            {% csrf_token %}
            <div class="text-center">
                <input class="btn btn-danger mt-3" type="submit" value="حذف">
            <a class="btn btn-info mt-3 back-btn" href="{% url 'user:detail' item.item_name item.id %}">تراجع</a>
 
            </div>
            </form>
    </div>
</div>
{% endblock content %}

templates/user/login.html
{% extends 'goldprice/base.html' %}
{% block content %}
<div class="gradient-examples">
    <div class="p-4 mb-5 text-right example linear" >
        <div class="border p-4" style="max-width: 400px;margin: auto; width: 100%;padding: 10px">
            <legend class="border-bottom pb-1 mb-3 text-center">تسجيل الدخول</legend>
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
                {{message}}
            </div>
            {% endfor %}
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">اسم المستخدم</label>
                    <input type="text" name="username" id="username" class="form-control" placeholder="قم بكتابة اسم المستخدم">
                </div>
                <div class="form-group">
                    <label for="password">كلمة المرور</label>
                    <input type="password" name="password" id="password" class="form-control" placeholder="كلمة المرور">
                </div>
                <div class="text-center">
                    <input class="btn btn-info pr-5 pl-5" type="submit" value="تسجيل الدخول">
                </div>
            </form>
            <div class="border-top mt-4 pt-2">
                <small>إذا لم يكن لديك حساب من قبل فيمكنك <a class="text-success" href="{% url 'user:singup' %}">التسجيل من هنا</a></small>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/user/profile.html
{% extends 'goldprice/base.html' %}
{% load static %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{message.tags}} text-right">
                {{message}}
            </div>
        {% endfor %}
    {% endif %}
    
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-7 border p-4 mb-5">
                <div class="card p-3 py-4">
                    
                    <div class="text-center">
                        <img src="{{user.profile.image.url}}" width="100" class="rounded-circle">
                    </div>
                    
                    <div class="text-center mt-3">
                        <span class="bg-secondary p-1 px-4 rounded text-white">{{user.username}}</span>
                        <h5 class="mt-2 mb-0">{{user.first_name}} {{user.last_name}}</h5>
                        <span>البريد الإلكتروني: <span class="font-weight-normal">{{user.email}}</span></span>
                        <!--
                         <ul class="social-list">
                            <li><i class="fa fa-facebook"></i></li>
                            <li><i class="fa fa-dribbble"></i></li>
                            <li><i class="fa fa-instagram"></i></li>
                            <li><i class="fa fa-linkedin"></i></li>
                            <li><i class="fa fa-google"></i></li>
                        </ul>
                        -->
                        <div class="buttons">
                            <!--
                            <button class="btn btn-outline-primary px-4">Message</button>
                            <button class="btn btn-primary px-4 ms-3" href="{% url 'user:profile_update' %}">تحرير</button>
                            -->
                            <a class="btn btn-primary px-4 ms-3" href="{% url 'user:profile_update' %}"><i
                                class="fas fa-pen fa-xs"></i> تحرير</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>

    <!--
    <div class="row mb-5 text-right">
        <div class="col-md">
            <h3 class="border-bottom pb-3 mb-4">عدد المنتجات التي نشرتها : <span class="text-info">({{items.count}})</span> </h3>
            <h4 class="bg-secondary text-center p-4 text-light">
                {{items.count}}
            </h4>

            <h3 class="border-bottom mb-4 pb-3 mt-5">منتجاتي</h3>
            {% for item in item_list %}
            <ul class="pr-2">
                <a class="text-dark" href="{% url 'user:detail' item.item_name item.id %}">{{item.item_name}}</a>
            </ul>
            {% empty %}
            <h4 class="text-center mb-5">لا يوجد منتجات</h4>
            {% endfor %}

            {% include 'blog/pagination.html' with page=item_list %}
            
        </div>
    </div>
    -->
    {% if not user.is_customer %}
    <div class="featured container no-gutter text-right">
        <h3 class="border-bottom pb-3 mb-4">عدد المنتجات التي نشرتها : <span class="text-info">({{items.count}})</span> </h3>
        <h3 class="border-bottom mb-4 pb-3 mt-5">منتجاتي</h3>
        <div class="row items">
            {% for item in item_list %}
            <div class="item new col-md-3">
            <a href="{% url 'user:detail' item.item_name item.id %}">
                <div class="featured-item">
                    {% if item.item_image %}
                            <img src="{{item.item_image.url}}" alt="">
                        {% else %}
                            <img class="card-img-top" src="{% static 'blog/img/defult.jpg' %}" alt="">
                    {% endif %}
                <!--<img src="{% static 'user/images/product-01.jpg'%}" alt="">-->
                <h4>{{item.item_name|safe}} </h4>
                <h6 class="mb-1"><span>£</span> {{item.price}} </h6>
                <p class="mb-0"><i class="fa fa-phone" aria-hidden="true"></i> الهاتف: {{item.phone_numb}}</p>
                <p><i class="fa fa-map-marker" aria-hidden="true"></i> العنوان: {{item.address}}</p>
                
                </div>
            </a>
            </div>
            {% endfor %}
            {% include 'blog/pagination.html' with page=item_list %}
        </div>
    </div>
    {%endif%}
    <style>
        
        
        .card{
            border:none;
        
            position:relative;
            overflow:hidden;
            border-radius:8px;
            cursor:pointer;
        }
        
        .card:before{
            
            content:"";
            position:absolute;
            left:0;
            top:0;
            width:4px;
            height:100%;
            background-color:#E1BEE7;
            transform:scaleY(1);
            transition:all 0.5s;
            transform-origin: bottom
        }
        
        .card:after{
            
            content:"";
            position:absolute;
            left:0;
            top:0;
            width:4px;
            height:100%;
            background-color:#8E24AA;
            transform:scaleY(0);
            transition:all 0.5s;
            transform-origin: bottom
        }
        
        .card:hover::after{
            transform:scaleY(1);
        }
        
        
        .fonts{
            font-size:11px;
        }
        
        .social-list{
            display:flex;
            list-style:none;
            justify-content:center;
            padding:0;
        }
        
        .social-list li{
            padding:10px;
            color:#8E24AA;
            font-size:19px;
        }
        
        
        .buttons button:nth-child(1){
               border:1px solid #8E24AA !important;
               margin-top: 20px;
               color:#8E24AA;
               height:40px;
        }
        
        .buttons button:nth-child(1):hover{
               border:1px solid #8E24AA !important;
               color:#fff;
               height:40px;
               background-color:#8E24AA;
        }
        .buttons {
            margin-top: 20px;
        }
        .buttons .btn:nth-child(1){
               border:1px solid #8E24AA !important;
               background-color:#8E24AA;
               color:#fff;
                height:40px;
        }
    </style>

{% endblock content %}

templates/user/singup.html
{% extends 'goldprice/base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<div class="gradient-examples" style="min-height:350px">
    <div class="p-4 mb-5 text-right example linear" >
        <div class="p-4 text-center" style="max-width: 500px;margin: auto; width: 100%;padding: 10px;">
                <h1 style='font-size: 24px;font-weight: bold;color:#ffffff'>يمكنك تسجيل الدخول كمستخدم أو كبائع</h1>
                <div class="container">
                    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2">
                        <div class="col p-3">
                          <p style="color: #DFB163;">يمكنك التسجيل كبائع فقط بالنقر على الزر أدناه</p>
                          <a href="{% url 'user:vendor_signup' %}"><button type="button" class="btn btn-primary btn-lg ">سجل كبائع</button></a>
                        </div>
                        <div class="col p-3">
                            <p style="color: #DFB163;">يمكنك التسجيل كمستخدم فقط بالنقر على الزر أدناه</p>
                            <a href="{% url 'user:customer_signup' %}"><button type="button" class="btn btn-info btn-lg">سجل كمستخدم</button></a>
                        </div>
                      
                    </div>
                  </div>
                
                
            </div>
    </div>
</div>
{% endblock content %}